### ISSUE TITLE
Create README

### ISSUE THREAD

**Issue by erin-doyle** [erin-doyle/react-timezone#3]
Also add badges for Travis build and Coveralls

**Comment by maitreyav** [comment]
I will work on this. Any special instructions?

**Comment by asotronot** [comment]
Added TravisCI and Coveralls badges into the Readme.md

**Comment by erin-doyle** [comment]
Oh awesome, I appreciate the help.  I'd like to start with install instructions followed by usage instructions.  There needs to be documentation of the following:

1. How to use the TimezoneAutocomplete component to include all required and optional props

1. How to use the injectTimezone Higher Order Component to include all of the props that are injected into the composed component

Finally I think there should be instructions on how to get the storybook running in order to see the example is use.

Thank you again for offering to help with this!
